server:
  port: 8081

spring:
  application:
    name: springboot-nyano
  datasource:
    url: jdbc:mysql://localhost:3307/db_ticketbox
    username: root
    password: 1234
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true